-- Create tables for EduDrive

-- 1. Subjects Table
create table subjects (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  semester int not null check (semester >= 3 and semester <= 8),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Resources Table
-- Storage of file metadata and extracted text for RAG
create table resources (
  id bigint generated by default as identity primary key,
  subject_id bigint references subjects(id) on delete cascade not null,
  title text not null,
  type text not null check (type in ('question_bank', 'lesson_pdf', 'reference_book')),
  file_url text not null, -- URL from Supabase Storage
  extracted_text text, -- content for AI to search
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table subjects enable row level security;
alter table resources enable row level security;

-- Policies
create policy "Public Read Subjects" on subjects for select using (true);
create policy "Public Insert Subjects" on subjects for insert with check (true);

create policy "Public Read Resources" on resources for select using (true);
create policy "Public Insert Resources" on resources for insert with check (true);
